### ISSUE TITLE
Unable to deploy Librum via Docker

### ISSUE THREAD

**Issue by mandraid** [Librum-Reader/Librum#88]
**Describe the bug**
Unable to run docker librum container.  It fails giving an error about getting the JWT key, even though it's been defined in the .yml file.  

**Error**
`Running in selfhosted mode, skipping AzureKeyVault configuration
Unhandled exception. System.IO.InvalidDataException: Failed getting the JWT Key
   at Presentation.DependencyInjection.ConfigureJwt(IServiceCollection services, IConfiguration configuration) in /app/src/Presentation/DependencyInjection.cs:line 136
   at Program.<Main>$(String[] args) in /app/src/Presentation/Program.cs:line 31
   at Program.<Main>(String[] args)
/var/lib/librum-server/srv/run.sh: line 4:     8 Aborted                 (core dumped) dotnet Presentation.dll
`

**Expected behavior**
The docker container should start up without issue. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by DavidLazarescu** [comment]
Please re-create this issue in Librum-Server
